### ISSUE TITLE
inconsistent information in *lsp-isar-progress*

### ISSUE THREAD

**Issue by gh-salt** [m-fleury/isabelle-release#22] opened 2020-05-04 12:42 UTC
In *lsp-isar-progress*, I have 
```
<Thy_Name> 1001 / 2001, ✖: 0, ⌛:0
```
although I am at the end of the `Thy_Name.thy` file.

**Comment by m-fleury** [comment] 2020-05-08 14:06
I cannot reproduce it.

**Comment by m-fleury** [comment] 2020-05-23 09:36
Duplicate of #28 with less information.

**Closed** 2020-05-23 09:36 UTC
Labels: duplicate, question
