### ISSUE TITLE
insert sledgehammer call at end of line has unexpected behaviour

### ISSUE THREAD

**Issue by gh-salt** [m-fleury/isabelle-release#17] opened 2020-03-08 17:02 UTC
When using the shortcut to insert sledgehammer ", i i" when on the last word of a line, the insertion happens after the first word of the line below.

Another annoying behavior (but this one is probably a feature) is the opening of the transient interface at insertion of sledgehammer, which blocks further editing. To me it would make more sense that sledgehammer is inserted by one command and the interface to insert the result is separated (in fact I never use the insertion of sledgehammer shortcut because of that).

**Comment by m-fleury** [comment] 2020-03-08 17:08
> Another annoying behavior (but this one is probably a feature) is the opening of the transient interface at insertion of sledgehammer, which blocks further editing. To me it would make more sense that sledgehammer is inserted by one command and the interface to insert the result is separated (in fact I never use the insertion of sledgehammer shortcut because of that).

Proposal: re-purpose «, i s» to insert sledgehammer.

**Comment by m-fleury** [comment] 2020-03-08 17:15
> When using the shortcut to insert sledgehammer ", i i" when on the last word of a line, the insertion happens after the first word of the line below.

I will have look. To reproduce where | is the cursor:

    lemma True
        using TrueI |


 It happens only when you already inserted the space after TrueI... if don't add it, it works correctly.

**Comment by m-fleury** [comment] 2020-03-08 17:58
I fixed the behaviour. The problems boils down to the following:

    word|
    (*whatever*)

I assumed that `word-at-point` (alias for `thing-at-point 'word`) would return `nil`. But no, that would be to easy! `word-at-point` returns word and `thing-at-point 'whitespace` returns `\n`.

**Comment by gh-salt** [comment] 2020-03-08 19:28
> (It never came to my mind that that this is easier than typing sh followed by TAB, but I have no strong opinion on that)

The problem is that the yas shortcuts were buggy for a while (they corrupted what was send to isabelle) so I completely stopped using them. Also, in spacemacs, sh TAB doesn't work (this is another thing we could look into another time),thus you have to type `sh Alt-/` , which requires more "effort" than `,is` (or typing sledgehammer completely).

**Comment by m-fleury** [comment] 2020-03-08 20:26
That is very annoying. Basically, here is an partial and non-great and ugly fix:


1. Force yasnippet to appear in the company result:

```
  ;; taken from reddit
   (defun mars/company-backend-with-yas (backends)
       "Add :with company-yasnippet to company BACKENDS.
  
   Taken from https://github.com/syl20bnr/spacemacs/pull/179."
       (if (and (listp backends) (memq 'company-yasnippet backends))
	   backends
	 (append (if (consp backends)
	 	    backends
	 	  (list backends))
	 	'(:with company-yasnippet))))

     ;; add yasnippet to all backends
     (setq company-backends
          (mapcar #'mars/company-backend-with-yas company-backends))
```

2. More configuration

```
     (auto-completion :variables
                      auto-completion-enable-snippets-in-popup t
                      auto-completion-tab-key-behavior 'complete
                      auto-completion-complete-with-key-sequence "jk"
                      auto-completion-complete-with-key-sequence-delay 0.1
                      auto-completion-enable-sort-by-usage t
                      auto-completion-idle-delay 0.1)
```

3. Then you will have the completion in the pop-up

![spacemacs_company](https://user-images.githubusercontent.com/41836833/76170545-3241bb00-6183-11ea-9712-cc61892d8e61.png)

It is still ugly because you rely on the popup, the results are ordered by usage, so it should eventually be the right order, and all this feels very un-spacemacsy (auto-completion-enable-snippets-in-popup should have worked).

**Comment by m-fleury** [comment] 2020-03-09 07:28
To make the solution work better, I could rename the keys (the stuff that get expanded like "lemma" in the screenshot above) such that they don't conflict with keywords (e.g., having "shave" ~> have «» or even éhave).

**Comment by m-fleury** [comment] 2020-03-17 10:36
After trying it out: using tab for both completion and indentation is a terrible idea.

**Comment by m-fleury** [comment] 2020-05-08 13:12
Duplicate of #10.

**Closed by m-fleury** 2020-05-08 13:12 UTC
Labels: bug, duplicate, enhancement
